- name: configure for apache
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
     - name: apache install
       yum: 
          name: apache2
          state: latest
     - name: start service
       service: 
          name: apache2
          state: started
     - name: copy files
       copy:
          src: /home/ubuntu/index.html
          dest: /var/www/html/index.html
          mode: '0755'