---
- hosts: prometheus
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus
    
- hosts: alertmanager
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - alertmanager
    
- hosts: prometheus_node_exporter
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter
    
- hosts: grafana
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana
    
